version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - "./php-wordpress:/var/www/html"
      - "./scripts-wordpress/wp-init-xdebug.sh:/usr/local/bin/apache2-custom.sh"
    command:
      - apache2-custom.sh

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./db-wordpress:/var/lib/mysql

